#!/usr/bin/env bash

set -e

#
# Nerves common post-build hook
#

NERVES_SYSTEM_BR_VERSION=$(cat "$BR2_EXTERNAL_NERVES_PATH/VERSION")
NERVES_SYSTEM_VERSION=$(cat "$NERVES_DEFCONFIG_DIR/VERSION")
NERVES_SYSTEM_NAME=$(basename "$NERVES_DEFCONFIG_DIR")

# Approximate an os-release
cat << EOF > "$TARGET_DIR/usr/lib/os-release"
NAME=Nerves
ID=nerves
NERVES_SYSTEM_BR_VERSION=$NERVES_SYSTEM_BR_VERSION
NERVES_SYSTEM_NAME=$NERVES_SYSTEM_NAME
NERVES_SYSTEM_VERSION=$NERVES_SYSTEM_VERSION
NERVES_BUILDROOT_VERSION=$BR2_VERSION
EOF

"$BR2_EXTERNAL_NERVES_PATH/scripts/scrub-target.sh" "$1"
